apiVersion: v1
kind: ConfigMap
metadata:
  name: aiocr-config
  namespace: aiocr
  labels:
    app: aiocr
data:
  APP_ENV: "production"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  CHROMA_PORT: "8001"
  MODEL_DIR: "/app/saved_models"
  TROCR_MODEL_PATH: "microsoft/trocr-base-handwritten"
  IMAGE_TARGET_SIZE: "64"
  MAX_IMAGE_SIZE_MB: "10"
